disabled_rules:
  - identifier_name
  - type_name
  - force_cast
  - function_body_length
  - type_body_length
  - file_length
  - line_length
    #- cyclomatic_complexity
  - for_where
  - function_parameter_count
  - large_tuple
  - nesting
  - trailing_whitespace
  - notification_center_detachment
  - multiple_closures_with_trailing_closure
  - todo
  - cyclomatic_complexity
    
excluded:
  - Frameworks
  - RussellDemo
  - RussellTests

number_separator:
  minimum_length: 5

