# Liulishuo Quicksilver  Project
#

stages:
  - lint
  - test
  - deploy

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
    #SLACK_USERNAME: "Harvest"
    #SLACK_CHANNEL: "#harvest_notification"
    
before_script:
  - bundle install

Lint: 
    script:
      - bundle exec fastlane lint
    type: lint
    tags: 
      - lint_swift5

Test:
    script: 
      - bundle exec fastlane test
    type: test
    only:
       - /^feature\/*/
       - /^hotfix\/*/
       - /^release\/*/
       - master
    tags:
       - Swift5

Deploy:
    script:
        - bundle exec fastlane sync_versions
    type: deploy
    only:
        - tags
    tags:
        - Xcode10_2
