disabled_rules:
  - identifier_name
  - nesting
  - function_parameter_count
  - large_tuple
  - function_body_length
  - type_name
  - file_length
  - force_cast
  - multiple_closures_with_trailing_closure
  #- function_body_length
  #- type_body_length
  #- file_length
  - line_length
  #- for_where
  #- function_parameter_count
  #- large_tuple
  #- nesting
  - trailing_whitespace
  #- notification_center_detachment
  #- multiple_closures_with_trailing_closure
  #- todo
  - cyclomatic_complexity

excluded:
  - Quicksilver/SubModule
  - Carthage/
  
number_separator:
  minimum_length: 5
